In [1]:
# importing the libraries
import numpy as np
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.neighbors import KDTree

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
# reading the data
person = pd.read_csv('famous_people.csv')

In [3]:
person.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Sno     39 non-null     int64 
 1   URI     39 non-null     object
 2   Name    39 non-null     object
 3   Text    39 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.3+ KB


In [5]:
person.head(10)

Sno                                              URI               Name  \
0    1      https://en.wikipedia.org/wiki/Narendra_Modi      Narendra Modi   
1    2        https://en.wikipedia.org/wiki/Sania_Mirza        Sania Mirza   
2    3        https://en.wikipedia.org/wiki/Virat_Kohli        Virat Kohli   
3    4        https://en.wikipedia.org/wiki/Miley_Cyrus        Miley Cyrus   
4    5  https://en.wikipedia.org/wiki/Leonardo_DiCaprio  Leonardo DiCaprio   
5    6       https://en.wikipedia.org/wiki/Barack_Obama       Barack Obama   
6    7       https://en.wikipedia.org/wiki/Donald_Trump       Donald Trump   
7    8     https://en.wikipedia.org/wiki/Kalpana_Chawla     Kalpana Chawla   
8    9       https://en.wikipedia.org/wiki/A._R._Rahman        A.R. Rahman   
9   10    https://en.wikipedia.org/wiki/Sunita_Williams    Sunita Williams   

                                                Text  
0  Narendra Damodardas Modi (Gujarati pronunciati...  
1  Sania Mirza (Hindustani pronunciation: [ˈsaːnɪ...  
2  Virat Kohli (About this soundpronunciation (he...  
3  Miley Ray Cyrus (born Destiny Hope Cyrus; Nove...  
4  Leonardo Wilhelm DiCaprio (/dɪˈkæprioʊ/, Itali...  
5  Barack Hussein Obama II (/bəˈrɑːk huːˈseɪn oʊˈ...  
6  Donald John Trump (born June 14, 1946) is the ...  
7  Kalpana Chawla (March 17, 1962 – February 1, 2...  
8  Allahrakka Rahman (About this soundpronunciati...  
9  Sunita Lyn Williams (née Pandya; born Septembe...

In [ ]:
# lower---> tokensize --> clean(stopwords and punctuation) --> lemmatize --> vector

In [6]:
# using tfidf vectoriser
tfidf = TfidfVectorizer()
train_tfidf = tfidf.fit_transform(person.Text)

In [8]:
train_tfidf.toarray()

array([[0.        , 0.01995272, 0.        , ..., 0.03617365, 0.        ,
        0.        ],
       [0.        , 0.02136063, 0.03973324, ..., 0.        , 0.03872613,
        0.        ],
       [0.05654498, 0.03773517, 0.03509589, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.03149592, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [9]:
tfidf.get_feature_names()

['000',
 '10',
 '100',
 '11',
 '11th',
 '12',
 '13',
 '13th',
 '14',
 '14th',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930',
 '1946',
 '1949',
 '1950',
 '1951',
 '1961',
 '1962',
 '1964',
 '1965',
 '1966',
 '1967',
 '1969',
 '1971',
 '1973',
 '1974',
 '1975',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1999',
 '19s',
 '1s',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2010s',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '205',
 '21',
 '22',
 '222',
 '23',
 '237',
 '23rd',
 '24',
 '25',
 '26',
 '27',
 '2700',
 '2800',
 '2882',
 '29',
 '2nd',
 '30',
 '300th',
 '31',
 '32',
 '33',
 '34',
 '348',
 '40',
 '42',
 '44',
 '44th',
 '45th',
 '50',
 '53',
 '643',
 '66th',
 '81st',
 '886',
 '897',
 '91',
 '911',
 '92',
 '

In [10]:
# adding the vector in tabe as column
person['tfidf'] = list(train_tfidf.toarray())

In [11]:
person

Sno                                                URI  \
0     1        https://en.wikipedia.org/wiki/Narendra_Modi   
1     2          https://en.wikipedia.org/wiki/Sania_Mirza   
2     3          https://en.wikipedia.org/wiki/Virat_Kohli   
3     4          https://en.wikipedia.org/wiki/Miley_Cyrus   
4     5    https://en.wikipedia.org/wiki/Leonardo_DiCaprio   
5     6         https://en.wikipedia.org/wiki/Barack_Obama   
6     7         https://en.wikipedia.org/wiki/Donald_Trump   
7     8       https://en.wikipedia.org/wiki/Kalpana_Chawla   
8     9         https://en.wikipedia.org/wiki/A._R._Rahman   
9    10      https://en.wikipedia.org/wiki/Sunita_Williams   
10   11         https://en.wikipedia.org/wiki/Yuvraj_Singh   
11   12     https://en.wikipedia.org/wiki/Deepika_Padukone   
12   13           https://en.wikipedia.org/wiki/Zayn_Malik   
13   14  https://en.wikipedia.org/wiki/Sushant_Singh_Ra...   
14   15         https://en.wikipedia.org/wiki/Selena_Gomez   
15   16       https://en.wikipedia.org/wiki/Vidit_Gujrathi   
16   17      https://en.wikipedia.org/wiki/Priyanka_Chopra   
17   18      https://en.wikipedia.org/wiki/Rannvijay_Singh   
18   19       https://en.wikipedia.org/wiki/Neil_Armstrong   
19   20         https://en.wikipedia.org/wiki/Bharti_Singh   
20   21         https://en.wikipedia.org/wiki/Suresh_Raina   
21   22    https://en.wikipedia.org/wiki/Viswanathan_Anand   
22   23         https://en.wikipedia.org/wiki/Harry_Styles   
23   24  https://en.wikipedia.org/wiki/Kapil_Sharma_(co...   
24   25             https://en.wikipedia.org/wiki/MS_Dhoni   
25   26    https://en.wikipedia.org/wiki/Biswa_Kalyan_Rath   
26   27       https://en.wikipedia.org/wiki/Magnus_Carlsen   
27   28          https://en.wikipedia.org/wiki/Chris_Gayle   
28   29        https://en.wikipedia.org/wiki/Courteney_Cox   
29   30       https://en.wikipedia.org/wiki/Shreya_Ghoshal   
30   31     https://en.wikipedia.org/wiki/Jennifer_Aniston   
31   32         https://en.wikipedia.org/wiki/Rohit_Shetty   
32   33   https://en.wikipedia.org/wiki/Ayushmann_Khurrana   
33   34               https://en.wikipedia.org/wiki/Ritviz   
34   35        https://en.wikipedia.org/wiki/Sandeep_Singh   
35   36        https://en.wikipedia.org/wiki/Darshan_Raval   
36   37       https://en.wikipedia.org/wiki/Ravi_Zacharias   
37   38       https://en.wikipedia.org/wiki/Kareena_Kapoor   
38   39          https://en.wikipedia.org/wiki/Irrfan_Khan   

                    Name                                               Text  \
0          Narendra Modi  Narendra Damodardas Modi (Gujarati pronunciati...   
1            Sania Mirza  Sania Mirza (Hindustani pronunciation: [ˈsaːnɪ...   
2            Virat Kohli  Virat Kohli (About this soundpronunciation (he...   
3            Miley Cyrus  Miley Ray Cyrus (born Destiny Hope Cyrus; Nove...   
4      Leonardo DiCaprio  Leonardo Wilhelm DiCaprio (/dɪˈkæprioʊ/, Itali...   
5           Barack Obama  Barack Hussein Obama II (/bəˈrɑːk huːˈseɪn oʊˈ...   
6           Donald Trump  Donald John Trump (born June 14, 1946) is the ...   
7         Kalpana Chawla  Kalpana Chawla (March 17, 1962 – February 1, 2...   
8            A.R. Rahman  Allahrakka Rahman (About this soundpronunciati...   
9        Sunita Williams  Sunita Lyn Williams (née Pandya; born Septembe...   
10          Yuvraj Singh  Yuvraj Singh (born 12 December 1981) is a form...   
11      Deepika Padukone  Deepika Padukone (pronounced [d̪iːpɪkaː pəɖʊko...   
12            Zayn Malik  Zain Javadd Malik (/ˈmælɪk/; born 12 January 1...   
13  Sushant Singh Rajput  Sushant Singh Rajput (21 January 1986 – 14 Jun...   
14          Selena Gomez  Selena Marie Gomez (born July 22, 1992) is an ...   
15       Vidit Gujarathi  Vidit Gujrathi (born 24 October 1994) is an In...   
16       Priyanka Chopra  Priyanka Chopra Jonas (pronounced [prɪˈjəŋkaː ...   
17       Rannvijay Singh  Rannvijay Singha (born 16 March 1983) is an In...   
18        Neil Armstro

In [16]:
kdtree = KDTree(train_tfidf.toarray())

In [25]:
distance, idx = kdtree.query(person.tfidf[2].reshape(1,-1) , k = 4)

In [26]:
distance , idx

(array([[0.        , 0.8497822 , 1.00579642, 1.06573571]]),
 array([[ 2, 24, 10, 20]]))

In [27]:
for i, value in list(enumerate(idx[0])):
    print(f"Name: {person['Name'][value]}")
    print(f'Distance: {distance[0][i]}')    
    print(f"URI: {person['URI'][value]}")    

Name: Virat Kohli
Distance: 0.0
URI: https://en.wikipedia.org/wiki/Virat_Kohli
Name: MS Dhoni
Distance: 0.8497822049958498
URI: https://en.wikipedia.org/wiki/MS_Dhoni
Name: Yuvraj Singh
Distance: 1.0057964199222786
URI: https://en.wikipedia.org/wiki/Yuvraj_Singh
Name: Suresh Raina
Distance: 1.0657357134257965
URI: https://en.wikipedia.org/wiki/Suresh_Raina


In [28]:
import joblib
# saving the model

# save the tfidf vocubulary
joblib.dump(tfidf , 'tfidf_vector_model.pkl')

# save the model
joblib.dump(kdtree , 'kdtree_model.pkl')

['kdtree_model.pkl']

In [29]:
#1

# loading the model
vector = joblib.load('tfidf_vector_model.pkl')

kd_model = joblib.load('kdtree_model.pkl')

In [37]:
# 2

user_input = input('please enter the description: ')

tf = vector.transform([user_input]).toarray()
tf

please enter the description: movie


array([[0., 0., 0., ..., 0., 0., 0.]])

In [38]:
distance, idx = kdtree.query(tf , k = 3)

In [39]:
for i, value in list(enumerate(idx[0])):
    print(f"Name: {person['Name'][value]}")
    print(f'Distance: {distance[0][i]}')    
    print(f"URI: {person['URI'][value]}")  

Name: Biswa Kalyan Rath
Distance: 1.3162777864551216
URI: https://en.wikipedia.org/wiki/Biswa_Kalyan_Rath
Name: Rannvijay Singh
Distance: 1.3465646947943446
URI: https://en.wikipedia.org/wiki/Rannvijay_Singh
Name: Selena Gomez
Distance: 1.386530527638578
URI: https://en.wikipedia.org/wiki/Selena_Gomez


In [ ]:
# task

clean the data

create a flask app